- fsevents.js
- package.json
Upgrade NaN to 1.5 to support io.js
Rework the `FSEvent` to avoid prototypal inheritance from a constructor that is backed by a `v8::ObjectTemplate` instance. Inherit from `EventEmitter` instead and mix in `Native.FSEvent` methods via a lightway proxy.
Kudos to @bnoordhuis for explaining the reason and showing a solution in https://github.com/bajtos/fsevents/pull/1
Before this change in place, the tests were failing on io.js 1.0.1 with
```
Assertion failed: (handle->InternalFieldCount() > 0), function Wrap, file /Users/bajtos/.node-gyp/1.0.1/src/node_object_wrap.h, line 56.
```
@pipobscure could you please review, land and release this PR as soon as reasonably possible? Your module is used e.g. by Karma test runner, thus most front-end people cannot upgrade to io.js until this fix is …
> Upgrade NaN to 1.5 to support io.js

- .travis.yml
- test/function.js
/to @bnoordhuis please review
/cc @pipobscure @es128
> Fix the tests and enable Travis CI

- .travis.yml
Multi OS support is a beta product and as a result it has to be requested and enabled for specific repositories. This makes it difficult for a user when they fork with the intention of submitting a PR. This change removes this dependency & instead just sets language to objective-c as this will ensure that an osx environment is used and since fsevents needs an osx environment and no other this results in the same behaviour.
> Remove travis multi-os configuration

- src/async.cc
- src/storage.cc
Calls to CFArrayRemoveAllValues() cause the CFArrayCallBacks retain
callback to get called with a NULL element pointer.  Bail out early
when that happens.
Fixes: https://github.com/strongloop/fsevents/issues/52
R=@es128 @bajtos
> src: fix NULL pointer dereference

- Readme.md
`json` code block highlighted comments as errors, changed language to `js` for better readability.
> json -> js code block in readme

- package.json
the 'install' lifecycle script is run too often; any `npm install` will trigger this rebuild, causing a lot of extra noise. Instead, the automatic support for `node-gyp` in npm should be used, and `npm rebuild` in the case of switching node versions or architectures.
> Remove duplicative lifecycle script

- fsevents.cc
- src/async.cc
- src/storage.cc
- src/thread.cc
It was observed from the core dump file that the crash occurred at `__CFArrayReleaseValues` of `CFArrayRemoveAllValues`. Analysis shows that when large number of items were added to a CFMutableArray, resizing of the container occurred. The resizing lead to `FSEventRelease` being prematurely called, causing the crash.
Therefore we store pointers in a plain vector to solve this problem.
> Use vector instead of CFMutableArray; fix #52

- .travis.yml
io.js v3.0 was released at 2015-08-04. https://github.com/nodejs/io.js/blob/master/CHANGELOG.md#2015-08-04-version-300-rvagg
> Add io.js 3.0 to Travis config

- .travis.yml
- Readme.md
- binding.gyp
- fsevents.js
- package.json
This change introduces node-pre-gyp which removes the need for end users to compile when installing fsevents. This means faster installs.
There are 2 possible ways in which a binary can published.
```bash
> node-pre-gyp rebuild
> node-pre-gyp package
> node-pre-gyp publish
```
When a new tag is created, as part of the travis build a binary will be created and published to a remote s3 bucket.
Specifying [publish binary] in the commit message will publish a binary if it has not already been published.
```bash
> git commit --allow-empty -m "[publish binary]"
> git push
```
This is presently facilitated using s3. I am using a free-tier account for the purpose of testing this change end-to-end. If this change is to be accepted then the test s3 endpoint should be switched to one under …
> Support for node-pre-gyp

- .gitignore
The pre-gyp addition introduces a `lib` dir that should not be checked in
> Add lib/ to .gitignore

- .travis.yml
- package.json
Resolves #97 by enforcing use of npm3+ for publishing and ensuring deps are flattened. `npm dedupe` needs to be run explicitly since node-pre-gyp bundles its own non-flattened deps.
Used `npm pack` to try to make sure this would remain compatible with older versions of npm/node, and it appears so. But it's hard to have 100% certainty about it without actually publishing to the npm registry and trying from there.
> Ensure bundled dependencies are staged cleanly

- fsevents.cc
- package.json
See [0] and [1]: starting with node.js v6, setting non-primitive values
on FunctionTemplate and ObjectTemplate instances is discouraged; v7 will
downright disallow it.  Update the code base.
[0] https://github.com/nodejs/node/issues/6216
[1] https://github.com/nodejs/node/pull/6228
Refs: https://github.com/strongloop/fsevents/issues/127
> Don't use deprecated v8::Template::Set().

- fsevents.js
- install.js
- package.json
eliminate platform warning when npm, yarn, etc
attempt to install on non darwin systems. this is
achieved by always installing, but artificially throwing
"Cannot find module 'fsevents'" when require()d
by dependents running on non darwin platform.
npm scripts entries also updated to bypass node-pre-gyp, etc.
when running on non darwin platform.
> install: better win, linux install experience

- .travis.yml
Experiment to see if my hunches in https://github.com/strongloop/fsevents/pull/169#issuecomment-306405202 are correct (or at least a step in the right direction.)
> Build binary for node v8

- install.js
Fixes #176 
Using `require.resolve` is better option to resolve module path because when installing fsevents with `npm install --no-bin-links fsevents` `spawn` can not find `node-pre-gyp` in `PATH`. If we use relative path `./node_modules/node-pre-gyp/bin/node-pre-gyp` in `spawn` call then this will error in case when packages are deduped and `node-pre-gyp` is located upper in file system tree.
Also see https://github.com/npm/npm/issues/10095
> Use require.resolve to resolve node-pre-gyp

- package.json
According to [node-pre-gyp's changelog](https://github.com/mapbox/node-pre-gyp/blob/master/CHANGELOG.md), this will also be necessary for node v9 support.
We can't rely on semver ranges because of the dependency bundling.
> Bump node-pre-gyp to 0.6.39

- .travis.yml
- fsevents.cc
- package.json
- src/methods.cc
Start with Nan 2.9.0 certain variants of `Nan::Callback::Call` are
deprecated. Overloads that preserve the async context are preferred
instead.
We associate a `Nan::AsyncResource` corresponding to a FSEvents instance.
This captures the async execution context which is restored when the
async callback is called.
For more information see https://github.com/nodejs/nan/blob/HEAD/doc/node_misc.md#nanasyncresource.
EDIT: this fixes the compile warnings that are presently displayed:
```
In file included from ../fsevents.cc:85:
../src/methods.cc:14:12: warning: 'Call' is deprecated [-Wdeprecated-declarations]
handler->Call(3, argv);
^
```
> fix: propagate async context

- fsevents.cc
- src/methods.cc
This PR fixes two bugs which I found while "stress-testing" the library with
```javascript
var fsevents = require("fsevents");
while(true) {
new fsevents.FSEvents("/", () => {});
}
```
and
```javascript
var fsevents = require("fsevents");
while(true) {
fsevents("/");
}
```
The first one is a SIGILL signal generated in `pthread_mutex_destroy` because the mutex is not always initialized. This is caused by not initializing `lockStarted` which causes it to sometimes be true, depending on where the object was allocated. A simple fix is to initialize it to `false`.
The other bug is a cyclic dependency which is hidden from v8 and therefore never freed. If the closure handed to FSEvents has a reference to the event and FSEvents saves the callback internally, a cyclic dependency is created. The …
> fix: possible SIGILL and memory leak

- .travis.yml
- package.json
As per https://github.com/strongloop/fsevents/issues/244#issuecomment-452984328
Why not, releasing NAPI will take until April, until then we'll just get complaints.
> Update to build for node v11

- src/fsevents.c
Resolves #259 the problem is simply that node has brought this out of experiemental so that
```CPP
#define NAPI_VERSION 3
#define NAPI_EXPERIMENTAL
#include <node_api.h>
```
no longer works and has to become
```CPP
#define NAPI_VERSION 4
#include <node_api.h>
```
> Set the correct NAPI Version now that this has come out of Experimental

- .gitignore
- .npmignore
- .travis.yml
- package.json
- test/fsevents.js
- test/function.js
- test/utils/run.js
This updates the node-pre-gyp dependency and removed the tap devDependency in favour of a very simple test-runner.
Tap used to be OK, but it has since taken on dependencies on everything and the kitchen sink. `npm audit` shows a security issue with a transitive dependency, which is why I decided to finally get rid of tap here too.
> Address Security Issue via node-pre-gyp/tar

- .travis.yml
- test/utils/fs.js
Time to 🎉 !!!
Node v8.16.0 is out, so we can add v8 to travis for future tests. In the meantime, up until now the fact that `fsevents` should work with v8.16 was theoretical. I've just tested the v11 pre-built binary against node v8.16.0 and it worked fine!!!
> Add v8 to travis & adapt test-harness

- src/rawfsevents.c
From the pthread docs: https://linux.die.net/man/3/pthread_cond_wait
> The pthread_cond_timedwait() and pthread_cond_wait() functions shall block on a condition variable. They shall be called with mutex locked by the calling thread or undefined behavior results.
That's why I moved unlock after `pthread_cond_wait`.
Also,
> It is important to note that when pthread_cond_wait() and pthread_cond_timedwait() return without error, the associated predicate may still be false.
That's why I added while loop to check for condition.
This was causing the following issue in Gatsby on OSX: https://github.com/gatsbyjs/gatsby/issues/17131
Due to strange race condition (most likely due to TurboBoost) `pthread_cond_signal` https://github.com/fsevents/fsevents/blob/d5cc566e83d74e5c8d7162773ee1a1dad7cfa0ca/sr …
> Fix random thread hanging due to incorrect pthread_cond_wait usage

- README.md
- fsevents.d.ts
- package.json
The v2 API is so simplified I think it shouldn't be a huge maintenance burden to keep the definition in this repo.
Types are based on the types in the README, plus the missing `cloned` event from #286. Constants were copied from the header file.
I'm unsure about the return type from `watch`. I based it on https://github.com/fsevents/fsevents/blob/e468f15134a1d19943f7c5d1d8d62ce1e60401c2/fsevents.js#L26-L30, but I don't know what the promise resolves to? Also, should it always return a `Promise` regardless of `instance === null` or not? Happy to tweak that part of the code.
EDIT: I've opened up a separate PR with the change to always return a Promise, and you can choose to accept that or not. I can tweak the type in this PR based on that conclusion: #296
> feat: add typescript definition

- README.md
- fsevents.js
As mentioned in #295, the return value of the stopper function seems inconsistent. This makes it always return `Promise<null>` regardless of when it's called.
An open question is - does `Native.stop` resolve with a value? I tested locally and it always resolved to `undefined`, so I'm thinking just resolving to `null` is fine. But I don't know C, so it might resolve to something else in some cases?
(I've also updated the readme with the new event from #286).
> feat: always return a promise from the stopper function

- ISSUE_TEMPLATE.md
- LICENSE
- README.md
- fsevents.js
- src/fsevents.c
- test/02_structure.js
- test/03_simple.js
- test/03_waiting.js
- test/04_emoji.js
Signed-off-by: Reece Dunham <me@rdil.rocks>
Also includes a bit of extra code cleanup, e.g. removing an unused import and changing OS X -> macOS (was renamed a few years ago)
> Bump license years

- install.js
- package.json
Fixes #301 
According to the [npm docs](https://docs.npmjs.com/misc/scripts#default-values), if a `binding.gyp` is detected, `npm` will run `node-gyp rebuild` by default unless an `install` script is specified. For some reason, even though `'OS=="mac"'` is specified in the `binding.gyp`, it builds on Windows anyway. This PR adds an `install` script that checks the platform and only runs `node-gyp rebuild` if a macOS environment is detected.
> Only build fsevents on macOS

- fsevents.cc
Initialize async member otherwise it may happen that in `FSEvents::asyncStart()` the check `async.data == this` is already `true` and as a result `uv_async_init()` is not called.
Refs.: https://github.com/nodejs/node/pull/34776#issuecomment-674314154
> Initialize async member

- fsevents.d.ts
> fix(typings): add return type to `watch` overload

- .github/workflows/nodejs.yml
- binding.gyp
Fixes #349 
I was able to verify that this works properly on my M1 and creates an universal binary that contains both an x86_64 slice and an arm64 slice. 
To verify:
```
$ file fsevents.node
fsevents.node: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit bundle x86_64] [arm64:Mach-O 64-bit bundle arm64]
fsevents.node (for architecture x86_64):        Mach-O 64-bit bundle x86_64
fsevents.node (for architecture arm64): Mach-O 64-bit bundle arm64
```
Should check that it continues working properly on x86_64 as well, I don't have an Intel machine any more to test, but I don't see any reason it wouldn't.
> fix: build universal binary (arm64/apple silicon)

- .github/workflows/nodejs.yml
- .github/workflows/publish.yml
- src/fsevents.c
The `napi_external` that maintains the watch on a file is closured into the *stop* function returned by `fsevents.watch`.
When that `napi_external` is garbage collected, the callback that was passed in is released and becomes uncallable. When it is called depsite this, the `napi_env` that is passed in is `NULL` which is intended by N-API as a signal  that the function is no longer usable. 
I ignored it in the past, because I always retain the stop function. However a test-script like the one provided provokes this. When garbage collection happens, the `napi_external` is cleared. However there may still be events in the pipeline. And that in turn triggers the crash in #355 .
I am now handling the `napi_env` as `NULL` signal properly by just dropping the event. In consequence, if you do not …
> fix: issue #355

- README.md
I spent a good amount of time trying to figure out why the watch would randomly stop working (or not work at all within workers), until I stumbled upon [this comment](https://github.com/fsevents/fsevents/issues/355#issuecomment-773626384) by @pipobscure in an unrelated thread.
Given that JS API don't generally have visible side effects on garbage collection, I think it's worth adding a very visible note 😅
> Adds a note about `stop` garbage collection

- README.md
getInfo() accepts two params, not three
https://github.com/fsevents/fsevents/blob/master/fsevents.js#L40
> Update README: pass 2 params to getInfo

- fsevents.js
When you scan a really large folder for file event changes, the client or kernel might not be able to keep up with all the initial 'add' events sent by fsevents.
This happens for me with our humongous vite project that has thousands of files that are sent to firefox. At some point today, chokidar receives undefined as file type when it's actually a rescan request, and fsevents / chokidar attempts to unlink the directory instead of rescanning it, making vite crash after a while instead of finishing processing fsevents.
This might be a fix in the correct direction, but the maintainers here are probably better at evaluating it. With this patch locally, vite no longer stops working for large projects on initial load.
> Handle MustScanSubDirs for large projects
